version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_APP_NAME=Sistema de Producción BUESTANFLOW
      - NEXT_PUBLIC_APP_VERSION=1.0.0
    restart: unless-stopped
    
  # Para futuras implementaciones con base de datos
  # db:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: buestanflow
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

# volumes:
#   postgres_data:
