#!/bin/bash

echo "📚 Comandos Git útiles para el proyecto:"
echo ""
echo "🔍 Ver estado de archivos:"
echo "git status"
echo ""
echo "➕ Agregar archivos específicos:"
echo "git add archivo.tsx"
echo ""
echo "➕ Agregar todos los cambios:"
echo "git add ."
echo ""
echo "💾 Hacer commit:"
echo "git commit -m 'descripción del cambio'"
echo ""
echo "⬆️ Subir cambios:"
echo "git push"
echo ""
echo "⬇️ Descargar cambios:"
echo "git pull"
echo ""
echo "📜 Ver historial:"
echo "git log --oneline"
echo ""
echo "🌿 Ver ramas:"
echo "git branch -a"
echo ""
echo "🔄 Cambiar de rama:"
echo "git checkout nombre-rama"
echo ""
echo "🆕 Crear nueva rama:"
echo "git checkout -b nueva-rama"
